version: '3'

services:
  main-server:
    build: ./main-server
    ports:
      - "5000:5000"
    volumes:
      - ./main-server:/app
    command: python Application.py

  secondary-server:
    build: ./secondary-server
    ports:
      - "5001:5000"
    volumes:
      - ./secondary-server:/app
    command: python Secondary.py
